name: Push Backend to Hugging Face

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  push-to-hf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Set up Hugging Face repo and Push
        run: |
          git remote add hf https://pushpit7:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/pushpit7/pollution-map || true
          git fetch hf main || true
          git checkout main || git checkout -b main
          git pull hf main --rebase || true
          
          git add .
          git commit -m "Auto-deploy update" || true
          git push hf main --force
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
