name: Push Backend to Hugging Face

on:
  push:
    paths:
      - '*'
    branches:
      - main
  workflow_dispatch:  # Allows the workflow to be manually triggered

jobs:
  push-to-hf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Initialize and Push to Hugging Face
        run: |
          rm -rf .git/
          git init
          git checkout -b main  # Use 'main' branch; change if needed
          git clone https://huggingface.co/spaces/pushpit7/pollution-map
          # Configure Git to use credentials
          git config credential.helper store
          echo "https://pushpit7:${{ secrets.HF_TOKEN }}@huggingface.co" > ~/.git-credentials

          git add .
          git commit -m "Initial commit"
          git push origin main --force
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
