name: Push Backend to Hugging Face

on:
  push:
    paths:
      - '*'
    branches:
      - main
  workflow_dispatch:  # Allows the workflow to be manually triggered

jobs:
  push-to-hf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push to Hugging Face
        run: |
          # Clone the Hugging Face repository using token authentication
          git clone https://pushpit7:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/pushpit7/pollution-map hf-repo
          
          # Copy your project files into the cloned repository (excluding .git directory)
          cp -r $(ls -A | grep -v "^\.git$" | grep -v "^hf-repo$") hf-repo/
          
          # Navigate to the HF repo directory
          cd hf-repo
          
          # Add and commit changes
          git add .
          git commit -m "Deploy to Hugging Face"
          
          # Push changes with token authentication
          git push https://pushpit7:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/pushpit7/pollution-map main
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
